// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: identity.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/gogo/protobuf/gogoproto"
	time "time"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *Login) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if this.Email == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, this.Email))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(this.RegInfo)); err != nil {
		return github_com_mwitkow_go_proto_validators.FieldError("RegInfo", err)
	}
	return nil
}

var _regex_Password_UID = regexp.MustCompile(`^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})?$`)

func (this *Password) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if !_regex_Password_UID.MatchString(this.UID) {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	if this.UID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}

var _regex_UserID_UID = regexp.MustCompile(`^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})?$`)

func (this *UserID) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if oneOfNester, ok := this.GetUser().(*UserID_UID); ok {
		if !_regex_UserID_UID.MatchString(oneOfNester.UID) {
			return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
		}
		if oneOfNester.UID == "" {
			return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
		}
	}
	if oneOfNester, ok := this.GetUser().(*UserID_Email); ok {
		if oneOfNester.Email == "" {
			return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, oneOfNester.Email))
		}
	}
	return nil
}

var _regex_BlockID_UID = regexp.MustCompile(`^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})?$`)

func (this *BlockID) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if !_regex_BlockID_UID.MatchString(this.UID) {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	if this.UID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	return nil
}
