// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: openid.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/mwitkow/go-proto-validators"
	time "time"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *Provider) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if this.Provider == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Provider", fmt.Errorf(`value '%v' must not be an empty string`, this.Provider))
	}
	if this.RedirectURI == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("RedirectURI", fmt.Errorf(`value '%v' must not be an empty string`, this.RedirectURI))
	}
	// Validation of proto3 map<> fields is unsupported.
	if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(this.RegInfo)); err != nil {
		return github_com_mwitkow_go_proto_validators.FieldError("RegInfo", err)
	}
	return nil
}
func (this *LoginURL) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if this.URL == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("URL", fmt.Errorf(`value '%v' must not be an empty string`, this.URL))
	}
	return nil
}
func (this *AuthCode) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if this.Provider == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Provider", fmt.Errorf(`value '%v' must not be an empty string`, this.Provider))
	}
	if this.State == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("State", fmt.Errorf(`value '%v' must not be an empty string`, this.State))
	}
	if this.Code == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Code", fmt.Errorf(`value '%v' must not be an empty string`, this.Code))
	}
	return nil
}
