// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/mwitkow/go-proto-validators"
	time "time"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

var _regex_User_UID = regexp.MustCompile(`^([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[4][a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})?$`)

func (this *User) Validate() error {
	if this.Domain == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Domain", fmt.Errorf(`value '%v' must not be an empty string`, this.Domain))
	}
	if !_regex_User_UID.MatchString(this.UID) {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	if this.UID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("UID", fmt.Errorf(`invalid unique identifier format`))
	}
	if this.Email == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, this.Email))
	}
	if this.Updated != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Updated); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Updated", err)
		}
	}
	if this.Properties != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Properties); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Properties", err)
		}
	}
	return nil
}
func (this *RegInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
